Ignore Windows builds for now due to missing DLL
Windows builds in Travis fail with this message — ignore Windows for
now.

The command "cargo test --verbose --all" exited with 127.

    Finished test [unoptimized + debuginfo] target(s) in 10.40s

     Running `C:\Users\travis\build\twilco\kosmonaut\target\debug\deps\kosmonaut-e0e8192cf750ed39.exe`

error: test failed, to rerun pass '--bin kosmonaut'

Caused by:

  process didn't exit successfully: `C:\Users\travis\build\twilco\kosmonaut\target\debug\deps\kosmonaut-e0e8192cf750ed39.exe` (exit code: 0xc0000135, STATUS_DLL_NOT_FOUND)

C:/Users/travis/.cargo/bin/cargo.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
/c/Users/travis/.casher/bin/casher: line 188: /c/Users/travis/.casher/cache-windows-1803-containers-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855--cargo-nightly.paths: No such file or directory